# Generated by Django 5.0.1 on 2024-02-03 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_is_user_added_alter_contest_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 4, 6, 19, 29, 992534, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='title',
            field=models.CharField(default='2024-02-03', max_length=15),
        ),
    ]
