# Generated by Django 5.0.1 on 2024-02-19 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_alter_contest_end_time_alter_contest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 18, 51, 2, 740329, tzinfo=datetime.timezone.utc)),
        ),
    ]
