apiVersion: v1
kind: Service
metadata:
  name: tensorits-backend-service
spec:
  selector:
    app: tensorits-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer