# Generated by Django 5.0.1 on 2024-02-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneVone', '0002_onevonenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='onevone',
            name='primary_user_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='onevone',
            name='secondary_user_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
