# Generated by Django 5.0.1 on 2024-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneVone', '0003_onevone_primary_user_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onevone',
            name='title',
            field=models.CharField(default='untitled', max_length=150),
        ),
    ]
