# Generated by Django 5.0.1 on 2024-03-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneVone', '0004_alter_onevone_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onevonenotification',
            name='oneVonesubmission',
        ),
        migrations.AddField(
            model_name='onevonenotification',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
