# Generated by Django 5.0.1 on 2024-02-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='condition',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='achievement',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
