# Generated by Django 5.0.1 on 2024-01-27 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('description', models.TextField(default='No description')),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('shape', models.JSONField(blank=True, null=True)),
                ('difficulty', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('solve_count', models.IntegerField(default=0)),
                ('try_count', models.IntegerField(default=0)),
                ('show_code', models.BooleanField(default=False)),
                ('addedAt', models.DateTimeField(auto_now_add=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('used_manipulator', models.JSONField(blank=True, null=True)),
                ('editorial_image', models.ImageField(null=True, upload_to='editorial_images/')),
                ('is_user_added', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('none', 'none'), ('up', 'up'), ('down', 'down')], default='none', max_length=10)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('test_case_verdict', models.JSONField(blank=True, null=True)),
                ('num_test_cases', models.IntegerField(default=5)),
                ('num_test_cases_passed', models.IntegerField(default=0)),
                ('taken_time', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('submission_no', models.IntegerField(default=1)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.JSONField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('test_case_no', models.IntegerField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
        ),
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
