# Generated by Django 5.0.1 on 2024-03-01 05:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_savedproblem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedproblem',
            unique_together={('user', 'problem')},
        ),
    ]
