name: Push CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    environment: Emtiaz_backend
    env:
      FIREBASE_ACCOUNT_TYPE: ${{ env.FIREBASE_ACCOUNT_TYPE }}
      FIREBASE_PROJECT_ID: ${{ env.FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY_ID: ${{ env.FIREBASE_PRIVATE_KEY_ID }}
      FIREBASE_PRIVATE_KEY: ${{ env.FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ env.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_CLIENT_ID: ${{ env.FIREBASE_CLIENT_ID }}
      FIREBASE_AUTH_URI: ${{ env.FIREBASE_AUTH_URI }}
      FIREBASE_TOKEN_URI: ${{ env.FIREBASE_TOKEN_URI }}
      FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
      FIREBASE_CLIENT_X509_CERT_URL: ${{ env.FIREBASE_CLIENT_X509_CERT_URL }}
      FIREBASE_UNIVERSE_DOMAIN: ${{ env.FIREBASE_UNIVERSE_DOMAIN }}
      DB_NAME: ${{ env.DB_NAME }}
      USER_NAME: ${{ env.USER_NAME }}
      PASSWORD: ${{ env.PASSWORD }}
      DB_SERVER_NAME: ${{ env.DB_SERVER_NAME }}
      DEBUG: ${{ env.DEBUG }}
      SECRET_KEY: ${{ env.SECRET_KEY }}
      ACR_LOGIN_SERVER: ${{ env.ACR_LOGIN_SERVER }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ env.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_ACCOUNT_KEY: ${{ env.AZURE_STORAGE_ACCOUNT_KEY }}
      DISK_URI: ${{ env.DISK_URI }}
      DOCKER_IMAGE_PATH: ${{ env.DOCKER_IMAGE_PATH }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Run Tests
      id: test
      run: |
        python backend/manage.py test
      env:
        FIREBASE_ACCOUNT_TYPE: ${{ env.FIREBASE_ACCOUNT_TYPE }}
        FIREBASE_PROJECT_ID: ${{ env.FIREBASE_PROJECT_ID }}
        FIREBASE_PRIVATE_KEY_ID: ${{ env.FIREBASE_PRIVATE_KEY_ID }}
        FIREBASE_PRIVATE_KEY: ${{ env.FIREBASE_PRIVATE_KEY }}
        FIREBASE_CLIENT_EMAIL: ${{ env.FIREBASE_CLIENT_EMAIL }}
        FIREBASE_CLIENT_ID: ${{ env.FIREBASE_CLIENT_ID }}
        FIREBASE_AUTH_URI: ${{ env.FIREBASE_AUTH_URI }}
        FIREBASE_TOKEN_URI: ${{ env.FIREBASE_TOKEN_URI }}
        FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
        FIREBASE_CLIENT_X509_CERT_URL: ${{ env.FIREBASE_CLIENT_X509_CERT_URL }}
        FIREBASE_UNIVERSE_DOMAIN: ${{ env.FIREBASE_UNIVERSE_DOMAIN }}
        DB_NAME: ${{ env.DB_NAME }}
        USER_NAME: ${{ env.USER_NAME }}
        PASSWORD: ${{ env.PASSWORD }}
        DB_SERVER_NAME: ${{ env.DB_SERVER_NAME }}
        DEBUG: ${{ env.DEBUG }}
        SECRET_KEY: ${{ env.SECRET_KEY }}
        ACR_LOGIN_SERVER: ${{ env.ACR_LOGIN_SERVER }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ env.AZURE_STORAGE_CONNECTION_STRING }}
        AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_ACCOUNT_KEY: ${{ env.AZURE_STORAGE_ACCOUNT_KEY }}
        DISK_URI: ${{ env.DISK_URI }}
        DOCKER_IMAGE_PATH: ${{ env.DOCKER_IMAGE_PATH }}

    - name: Run Collectstatic
      run: |
        python backend/manage.py collectstatic --noinput

    - name: Run Migration
      run: |
        python backend/manage.py makemigrations --noinput

    - name: Run Migrate
      run: |
        python backend/manage.py migrate --noinput

    - name: Azure ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }} 
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      if: steps.test.outcome == 'success'
      working-directory: backend
      run: |
        docker build -t ${{ secrets.ACR_USERNAME }}.azurecr.io/tensorits-backend-image:${{ github.sha }} .
        docker push ${{ secrets.ACR_USERNAME }}.azurecr.io/tensorits-backend-image:${{ github.sha }}

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: latest

    - name: Login to Azure Container Registry
      if: steps.test.outcome == 'success'
      run: az acr login --name ${{ secrets.ACR_USERNAME }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

    - name: Azure AKS Login
      if: steps.test.outcome == 'success'
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Deploy to AKS
      if: steps.test.outcome == 'success'
      run: |
        kubectl apply -f backend/kubernetes/deployment.yaml
        kubectl apply -f backend/kubernetes/service.yaml

    - name: Log and Notify on Failure
      if: steps.test.outcome == 'failure'
      run: |
        echo "Tests failed. Notify relevant parties or log the failure details."
