name: Pull Request CI

on:
  pull_request:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Emtiaz_backend
    env:
      FIREBASE_ACCOUNT_TYPE: ${{ env.FIREBASE_ACCOUNT_TYPE }}
      FIREBASE_PROJECT_ID: ${{ env.FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY_ID: ${{ env.FIREBASE_PRIVATE_KEY_ID }}
      FIREBASE_PRIVATE_KEY: ${{ env.FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ env.FIREBASE_CLIENT_EMAIL }}
      FIREBASE_CLIENT_ID: ${{ env.FIREBASE_CLIENT_ID }}
      FIREBASE_AUTH_URI: ${{ env.FIREBASE_AUTH_URI }}
      FIREBASE_TOKEN_URI: ${{ env.FIREBASE_TOKEN_URI }}
      FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
      FIREBASE_CLIENT_X509_CERT_URL: ${{ env.FIREBASE_CLIENT_X509_CERT_URL }}
      FIREBASE_UNIVERSE_DOMAIN: ${{ env.FIREBASE_UNIVERSE_DOMAIN }}
      DB_NAME: ${{ env.DB_NAME }}
      USER_NAME: ${{ env.USER_NAME }}
      PASSWORD: ${{ env.PASSWORD }}
      DB_SERVER_NAME: ${{ env.DB_SERVER_NAME }}
      DEBUG: ${{ env.DEBUG }}
      SECRET_KEY: ${{ env.SECRET_KEY }}
      ACR_LOGIN_SERVER: ${{ env.ACR_LOGIN_SERVER }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ env.AZURE_STORAGE_CONNECTION_STRING }}
      AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_ACCOUNT_KEY: ${{ env.AZURE_STORAGE_ACCOUNT_KEY }}
      DISK_URI: ${{ env.DISK_URI }}
      DOCKER_IMAGE_PATH: ${{ env.DOCKER_IMAGE_PATH }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        pip install -r backend/requirements.txt

    - name: Run Tests
      run: |
        python backend/manage.py test
      env:
        FIREBASE_ACCOUNT_TYPE: ${{ env.FIREBASE_ACCOUNT_TYPE }}
        FIREBASE_PROJECT_ID: ${{ env.FIREBASE_PROJECT_ID }}
        FIREBASE_PRIVATE_KEY_ID: ${{ env.FIREBASE_PRIVATE_KEY_ID }}
        FIREBASE_PRIVATE_KEY: ${{ env.FIREBASE_PRIVATE_KEY }}
        FIREBASE_CLIENT_EMAIL: ${{ env.FIREBASE_CLIENT_EMAIL }}
        FIREBASE_CLIENT_ID: ${{ env.FIREBASE_CLIENT_ID }}
        FIREBASE_AUTH_URI: ${{ env.FIREBASE_AUTH_URI }}
        FIREBASE_TOKEN_URI: ${{ env.FIREBASE_TOKEN_URI }}
        FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
        FIREBASE_CLIENT_X509_CERT_URL: ${{ env.FIREBASE_CLIENT_X509_CERT_URL }}
        FIREBASE_UNIVERSE_DOMAIN: ${{ env.FIREBASE_UNIVERSE_DOMAIN }}
        DB_NAME: ${{ env.DB_NAME }}
        USER_NAME: ${{ env.USER_NAME }}
        PASSWORD: ${{ env.PASSWORD }}
        DB_SERVER_NAME: ${{ env.DB_SERVER_NAME }}
        DEBUG: ${{ env.DEBUG }}
        SECRET_KEY: ${{ env.SECRET_KEY }}
        ACR_LOGIN_SERVER: ${{ env.ACR_LOGIN_SERVER }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ env.AZURE_STORAGE_CONNECTION_STRING }}
        AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_ACCOUNT_KEY: ${{ env.AZURE_STORAGE_ACCOUNT_KEY }}
        DISK_URI: ${{ env.DISK_URI }}
        DOCKER_IMAGE_PATH: ${{ env.DOCKER_IMAGE_PATH }}

    - name: Run Collectstatic
      run: |
        python backend/manage.py collectstatic --noinput
    - name: Run Migration
      run: |
        python backend/manage.py makemigrations --noinput
    - name: Run Migrate
      run: |
        python backend/manage.py migrate --noinput